import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from "../components/header";
import TitleText from "../components/title_text";
import InfoBlock from "../components/Info_block";
import ProfileBlock from "../components/profile_block";
import ProjectBlock from "../components/project_peview";
import InfoBlockGrid from "../components/Info_block_grid";
import HeaderGrid from "../components/header_grid";
import TitleTextGrid from "../components/title_text_grid";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Header></Header> */}
      <HeaderGrid/>
      <main className={styles.main}>
<<<<<<< HEAD
          {/* <TitleText></TitleText> */}
          <TitleTextGrid/>
=======
          <TitleText></TitleText>
>>>>>>> 916691f53e42fce4ef9f23c1e7ed279604873a1a
      </main>
        <InfoBlockGrid/>
        <InfoBlock></InfoBlock>
        <ProfileBlock></ProfileBlock>
        <ProjectBlock></ProjectBlock>
      <footer className={styles.footer}>
        футер
      </footer>
    </div>
  )
}
